### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#112]
Several parts of doc (https://spine-generic.readthedocs.io/en/latest/) need to be updated:

- [ ] [Quality control](https://spine-generic.readthedocs.io/en/latest/documentation.html#quality-control) section - replace segmentation and vertebral labeling sh codes with help for `manual_corection.py` script - related to https://github.com/spine-generic/spine-generic/issues/44, https://github.com/spine-generic/spine-generic/issues/85 and https://github.com/spine-generic/spine-generic/pull/103 and https://github.com/spine-generic/spine-generic/issues/119

- [x] [Contributors](https://spine-generic.readthedocs.io/en/latest/documentation.html#contributors) section - fix relative link to _contribution guidelines_ - related to https://github.com/spine-generic/spine-generic/issues/100 and https://github.com/spine-generic/spine-generic/pull/102

- [ ] [Generate figures](https://spine-generic.readthedocs.io/en/latest/documentation.html#generate-figures) section - `generate_figure.py` script no longer needs on input `parameters.sh` file; update usage of this script - related to https://github.com/spine-generic/spine-generic/issues/111

- [ ] [Data conversion: DICOM to BIDS](https://spine-generic.readthedocs.io/en/latest/documentation.html#data-conversion-dicom-to-bids) section - link to `config_spine.txt` file is broken - fix it

**Comment by jcohenadad** [comment]
@valosekj you can add this issue in [this section](https://spine-generic.readthedocs.io/en/latest/documentation.html#id2):
![Screen Shot 2020-07-08 at 12 37 18 PM](https://user-images.githubusercontent.com/2482071/86946097-e0e90e80-c117-11ea-8323-116ee18c15d0.png)

**Comment by valosekj** [comment]
> @valosekj you can add this issue in [this section](https://spine-generic.readthedocs.io/en/latest/documentation.html#id2):
> ![Screen Shot 2020-07-08 at 12 37 18 PM](https://user-images.githubusercontent.com/2482071/86946097-e0e90e80-c117-11ea-8323-116ee18c15d0.png)

Thanks 👍 , already added as the forth point.

**Comment by jcohenadad** [comment]
@valosekj if you are already working on a branch please submit a PR asap (because others might be updating the doc in parallel)-- thx

**Comment by valosekj** [comment]
Is it better to fix each point listed above in single PR or fix all points together in one PR?

**Comment by jcohenadad** [comment]
> Is it better to fix each point listed above in single PR or fix all points together in one PR?

i would do it in one PR-- but then you should do it quickly-- we don't want to have a PR dragging for several weeks, because it will "block" parallel developments on the same files

**Comment by valosekj** [comment]
Sure, I will do it tomorrow.
